server:
  port: 8083
  servlet:
    context-path: /transaction

spring:
  application:
    name: transaction
  datasource:
    url: jdbc:mysql://localhost:3306/transaction
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
